### ISSUE TITLE
RFC: Save thumbnails feature

### ISSUE THREAD

**Issue by LordSimal** [passchn/cakephp-assets#6]
The current implementation re-renders every image on every request which can be quite process intensive.

It would be better if given thumbnail sizes are only generated once and then referenced via a URL.

This of course means we would need at least a separate table which contains thumbnail sizes and a junction table which connects assets to their respective thumbnail size entities.

This also would imply, that changes in the "base" asset would trigger a re-render of all already generated thumbnail sizes.

What do you think about that?

**Comment by passchn** [comment]
The images are not actually re-rendered on every request. The `ImageAsset` Utility tries to find an existing file based on its modifications. If a matching file exists, it is returned directly, otherwise it will be rendered and saved. 

See: https://github.com/brandcom/cakephp-assets/blob/3579a43f07301d6fe31f68f59f521cd87f0c347f/src/Utilities/ImageAsset.php#L380 

The only "problem" is: If there was no request, no scaled image will be rendered. 

I usually solve it in this way: If I e.g. want to use resized images in JavaScript through a JSON response, I would create virtual properties on e.g. a `Product` as `$product_image_sm`, `$product_image_lg` etc., so the scaled Image will be rendered on the first request to the JSON Api. 

I never really felt the need to render thumbnails directly after uploading and also, I never know what sizes I will need in the template. Product images will be displayed in other sizes than user profile images etc.

**Comment by LordSimal** [comment]
Seems like I missunderstood how this works. Already rendered images indeed do not get re-rendered, no matter if they are the original image or if they are a scaled, converted image... It just felt to me like it does the converting and scaling part everytime. Thanks for the clarification 😄

**Comment by passchn** [comment]
No, it's just creating an md5 sum of a fancy array every time :)
